include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_child_properties_last: true
    constant_identifier_names: false

    # Negate these when debugging
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: false
    avoid_print: false